(define (problem slove)
    (:domain logistic)
    (:objects
        driver1 driver2 truck1 truck2 ship plane package1 package2 package3 package4 airwp seawp wp1 wp2 wp3 wp4 wp5 wp6 wp7 wp8 wp9 wp10 wp11
    )

    (:init
        ;todo: put the initial state's facts and numeric values here
        (driver driver1)
        (driver driver2)
        (truck truck1)
        (truck truck2)
        (ship ship)
        (plane plane)
        (package package1)
        (package package2)
        (package package3)
        (package package4)
        (= (dis airwp wp2) 20)
        (= (dis wp2 airwp) 20)
        (= (dis airwp wp4) 20)
        (= (dis wp4 airwp) 20)
        (= (dis wp7 seawp) 75)
        (= (dis seawp wp7) 75)
        (= (dis wp1 wp2) 100)
        (= (dis wp2 wp1) 100)
        (= (dis wp2 wp3) 100)
        (= (dis wp3 wp2) 100)
        (= (dis wp3 wp8) 75)
        (= (dis wp8 wp3) 75)
        (= (dis wp8 wp11) 75)
        (= (dis wp11 wp8) 75)
        (= (dis wp11 wp10) 100)
        (= (dis wp10 wp11) 100)
        (= (dis wp9 wp10) 100)
        (= (dis wp10 wp9) 100)
        (= (dis wp9 wp4) 75)
        (= (dis wp4 wp9) 75)
        (= (dis wp4 wp1) 75)
        (= (dis wp1 wp4) 75)
        (= (dis wp1 wp5) 100)
        (= (dis wp5 wp1) 100)
        (= (dis wp5 wp6) 50)
        (= (dis wp6 wp5) 50)
        (= (dis wp2 wp6) 75)
        (= (dis wp6 wp2) 75)
        (= (dis wp6 wp7) 50)
        (= (dis wp7 wp6) 50)
        (wp airwp)
        (wp seawp)
        (wp wp1)
        (wp wp2)
        (wp wp3)
        (wp wp4)
        (wp wp5)
        (wp wp6)
        (wp wp7)
        (wp wp8)
        (wp wp9)
        (wp wp10)
        (wp wp11)
        (driverat wp1 driver1)
        (driverat wp4 driver2)
        (truckat wp6 truck1)
        (truckat wp9 truck2)
        (packageat wp2 package1)
        (packageat wp3 package2)
        (packageat wp5 package3)
        (packageat wp11 package4)
        (planeat airwp)
        (shipat seawp)
        (airconnected wp2 airwp)
        (airconnected wp4 airwp)
        (seaconnected wp7 seawp)
        (connected wp1 wp5)
        (connected wp1 wp4)
        (connected wp1 wp2)
        (connected wp4 wp9)
        (connected wp9 wp10)
        (connected wp10 wp11)
        (connected wp11 wp8)
        (connected wp8 wp3)
        (connected wp3 wp2)
        (connected wp2 wp6)
        (connected wp6 wp7)
        (connected wp6 wp5)
        (empty truck1)
        (empty truck2)
    )

    (:goal
        (and
            ;todo: put the goal condition here
            (driverat wp1 driver1)
            (driverat wp1 driver2)
            (packageat wp9 package1)
            (packageat wp9 package3)
            (packageat seawp package2)
            (packageat wp2 package4))
    )
)

;un-comment the following line if metric is needed
;(:metric minimize (???))